bash_src := env_var_or_default("BASH_SRC", home_directory() / "source/bash")

# Apply patch and build bash with --dump-ast support
build:
    cd {{bash_src}} && git checkout -- . && rm -f dump_ast.c dump_ast.h && git apply {{justfile_directory()}}/bash-dump-ast.patch
    cd {{bash_src}} && make clean && ./configure && make -j$(nproc)
    cp {{bash_src}}/bash {{justfile_directory()}}/bash-oracle

# Test the oracle
test: build
    echo 'echo hello world' | ./bash-oracle --dump-ast
    echo 'for i in a b; do echo $i; done' | ./bash-oracle --dump-ast
    echo 'if true; then echo yes; else echo no; fi' | ./bash-oracle --dump-ast

# Clean
clean:
    rm -f bash-oracle
    cd {{bash_src}} && git checkout -- . && rm -f dump_ast.c dump_ast.h
